import { uuid } from "uuidv4";

const matchExample = {
    homeTeam: "New York Knicks",
    homeTeamScore: 0,
    homeTeamPlayers: [
        {         
        id: uuid(),
        firstName: "Kevin",
        lastName: "Knox",
        jerseyNumber: "20",
        position: "SF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }        
        },
        {            
        id: uuid(),
        firstName: "Portis",
        lastName: "Bobby",
        jerseyNumber: "1",
        position: "PF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Randle",
        lastName: "Julius",
        jerseyNumber: "30",
        position: "PF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Mitchell",
        lastName: "Robinson",
        jerseyNumber: "23",
        position: "C",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "RJ",
        lastName: "Barret",
        jerseyNumber: "9",
        position: "SG",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Frank",
        lastName: "Ntillikina",
        jerseyNumber: "11",
        position: "PG",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Taj",
        lastName: "Gibson",
        jerseyNumber: "67",
        position: "C",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Damyean",
        lastName: "Dotson",
        jerseyNumber: "21",
        position: "SG",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
    ],
    awayTeam: "Los Angeles Lakers",
    awayTeamScore: 0,
    awayTeamPlayers: [
        {            
        id: uuid(),
        firstName: "Lebron",
        lastName: "James",
        jerseyNumber: "23",
        position: "SF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Anthony",
        lastName: "Davis",
        jerseyNumber: "3",
        position: "PF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Kyle",
        lastName: "Kuzma",
        jerseyNumber: "0",
        position: "PF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Markief",
        lastName: "Morris",
        jerseyNumber: "88",
        position: "PF",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Rajon",
        lastName: "Rondo",
        jerseyNumber: "9",
        position: "PG",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "JR",
        lastName: "Smith",
        jerseyNumber: "21",
        position: "SG",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Dwight",
        lastName: "Howard",
        jerseyNumber: "39",
        position: "C",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
        {            
        id: uuid(),
        firstName: "Danny",
        lastName: "Green",
        jerseyNumber: "14",
        position: "SG",
        stats:{
            FGA: 0,
            FGM: 0,
            TPA: 0,
            TPM: 0,
            FTA: 0,
            FTM: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            PTS: 0,
            }            
        },
    ],


}


export default matchExample